#查看springboot开启了哪些配置
debug: false

spring:
  profiles:
    active: dev


---
#开发环境配置
spring:
  profiles: dev

server:
  port: 8090

logging:
  config: classpath:log4j2_dev.xml


---
#测试环境配置
spring:
  profiles: test

server:
  port: 8091


---
#生产环境配置

spring:
  profiles: pro

server:
  port: 8092